site_name: How to Make Rain
theme:
  favicon: img/favicon.ico
  logo: img/drop.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
  - Index: index.md
  - Intro to Cloud Physics: meteorology.md
  - Seeding Process: seeding.md
  - Conditions: seeding_conditions.md
  - Seeding Types: seeding_types.md
  - Anthropogenic Impact: impact.md
  - Project SNOWIE: SNOWIE.md
  - WWMPP: WWMPP.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format